# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddoc',
            name='version',
            field=models.IntegerField(blank=True, default=0, verbose_name='version'),
        ),
    ]
